In [1]:
import pandas as pd
import numpy as np
import matplotlib .pyplot as plt
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score



In [2]:
sona=pd.read_csv('sonar_all.csv',names=range(0,61),header=0)


In [3]:
sona.head()

0       1       2       3       4       5       6       7       8   \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

       9   ...      51      52      53      54      55      56      57  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   

       58      59  60  
0  0.0052  0.0044   R  
1  0.0095  0.0078   R  
2  0.0040  0.0117   R  
3  0.0107  0.0094   R  
4  0.0051  0.0062   R  

[5 rows x 61 columns]

In [4]:
sona.shape

(207, 61)

In [5]:
x=sona.iloc[:,0:-1]
x.shape

(207, 60)

In [6]:
pca=PCA(n_components=10)

In [7]:
y=sona.iloc[:,-1]

In [8]:
x=pca.fit_transform(x)

In [9]:
x.shape

(207, 10)

In [10]:
pd.DataFrame(data=x)

0         1         2         3         4         5         6  \
0   -0.970285  1.017654  0.830432  0.120147  0.299120  0.202682 -0.226988   
1   -0.324435  0.876876  0.228203  0.868926  0.098053 -0.269122 -0.421778   
2    0.853571  0.697734 -0.023602 -0.123425 -0.584388  0.351808  0.478187   
3   -0.061337  0.226034  0.635198  0.152907  0.150982  0.081111 -0.374523   
4   -0.605423  0.901962  0.804550  0.271896  0.496832  0.464410 -0.224909   
5   -0.155512  0.397189 -0.236508 -0.184495 -0.219554  0.377336  0.022937   
6   -0.605470 -0.050505  0.001244 -0.237550 -0.664685  0.061253 -0.135593   
7   -0.381704 -0.075134 -0.029934 -0.257844 -0.536723 -0.506412  0.099131   
8   -0.176107 -1.010684  0.088104 -0.314870  0.007677 -0.104833  0.208576   
9    1.121184 -0.458966  0.177197 -0.288348  0.310049 -0.208691 -0.029574   
10  -0.106705 -0.263267  0.039528 -0.319364 -0.391495 -0.422232 -0.284659   
11  -0.940904  0.224908 -0.152609 -0.704344 -0.224894 -0.193290  0.345440   
12   0.425360  0.056089  0.015738 -0.129001  0.030468  0.348219 -0.198542   
13   0.051528  0.192575  0.009238 -0.401783 -0.485005  0.110280 -0.178216   
14   0.491857  0.483175 -0.202715 -0.209316  0.481878  0.066035 -0.104808   
15   0.957630  0.409409 -0.123540  0.057410  0.046969  0.037284  0.053658   
16  -0.271263  0.920524 -0.328589 -0.421034 -0.090029  0.598527  0.155193   
17   0.490338 -0.208931 -0.250739  0.013894  0.671392  0.079170 -0.354134   
18  -1.348339  0.640596  0.239897  0.174964 -0.383288 -0.048684 -0.057778   
19   0.231539  0.847275 -0.601103  0.042717  0.085349 -0.462631  0.291277   
20   1.064569  1.371856 -0.010159  0.241052  0.259810  0.016913 -0.077623   
21   1.591744  1.206355  0.186906  0.140388 -0.352558  0.462588  0.262794   
22   0.839770 -0.091457  0.180911 -0.027746  0.536786 -0.454186 -0.102716   
23   1.272468  0.633873  0.041001 -0.620160  0.484712 -0.222344  0.483404   
24   1.122370 -0.534688 -0.402314  0.007445  0.500027 -0.281233  0.440886   
25  -0.913345  0.132064  0.078133 -0.365047  0.036030  0.036367  0.167238   
26  -0.333431 -0.435699  0.314493  0.016409  0.404244  0.286652  0.114079   
27  -0.674347  0.559539 -0.251874 -0.398369 -0.146109 -0.151630  0.030528   
28  -0.335773 -0.093118  0.713440 -0.184253 -0.079845 -0.056423 -0.233137   
29  -0.084998 -0.423465  0.051034  0.012157  0.156758  0.043469 -0.221829   
..        ...       ...       ...       ...       ...       ...       ...   
177  0.306020 -0.646297  0.241600 -0.022086  0.009268 -0.129839  0.061039   
178  0.291160 -0.454656  0.084138  0.277234  0.160674 -0.214163  0.233465   
179 -0.155897 -0.350416 -0.061307  0.615945 -0.560529 -0.235360  0.024765   
180  0.370414 -0.231302  0.010363  0.870798 -0.459328  0.220704  0.207816   
181  0.152069 -0.174330 -0.012127  0.783319 -0.367743 -0.037895 -0.070156   
182  0.052993 -0.286210 -0.165607  0.854433 -0.423896 -0.027690 -0.065236   
183 -0.289793 -0.219833 -0.103814  0.637888 -0.702174 -0.169219 -0.236387   
184 -0.127243 -0.315968 -0.134459  0.824269 -0.530716 -0.193142 -0.056837   
185  0.612040 -0.140907  0.414713  0.923423 -0.274005  0.186291  0.500590   
186  0.538390 -0.406372  0.640594  0.259354 -0.035018 -0.070475  0.102055   
187  0.482475 -0.574662  0.564374  0.129783 -0.089619 -0.072145  0.083185   
188  0.258542 -0.607596  0.504631  0.099862 -0.004531 -0.117051 -0.043023   
189  0.366702 -0.659581  0.491892  0.065553 -0.011654 -0.023369 -0.001823   
190  0.273982 -0.737167  0.459841  0.004325 -0.091029  0.048325 -0.025466   
191  0.235252 -0.745730  0.538385 -0.007782 -0.092164 -0.001920 -0.036003   
192  0.423267 -0.730424  0.450763  0.003781 -0.066970 -0.007834 -0.001557   
193  0.092906 -0.962154  0.255198  0.111072 -0.043990 -0.174753 -0.064150   
194 -0.308393 -0.929487  0.096720  0.215664 -0.216991 -0.171219  0.019095   
195 -0.498100 -0.943673 -0.036998  0.140693 -0.222871 -0.267697 -0.062500   
196 -0.360313 -0.913039 -0.030093  0.046618 -0.232083 -0.208407 -0.006618   
197 -0.3

In [11]:
y

0      R
1      R
2      R
3      R
4      R
5      R
6      R
7      R
8      R
9      R
10     R
11     R
12     R
13     R
14     R
15     R
16     R
17     R
18     R
19     R
20     R
21     R
22     R
23     R
24     R
25     R
26     R
27     R
28     R
29     R
      ..
177    M
178    M
179    M
180    M
181    M
182    M
183    M
184    M
185    M
186    M
187    M
188    M
189    M
190    M
191    M
192    M
193    M
194    M
195    M
196    M
197    M
198    M
199    M
200    M
201    M
202    M
203    M
204    M
205    M
206    M
Name: 60, Length: 207, dtype: object

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
#standard scale
scale=StandardScaler()

In [14]:
x=scale.fit_transform(x)

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.22,random_state=45)

In [16]:
lr=LogisticRegression()


In [17]:
lr.fit(x_train,y_train)
lr.score(x_train,y_train)
predlr=lr.predict(x_test)
print(accuracy_score(y_test,predlr))
print(confusion_matrix(y_test,predlr))
print(classification_report(y_test,predlr))


0.8043478260869565
[[23  1]
 [ 8 14]]
              precision    recall  f1-score   support

           0       0.74      0.96      0.84        24
           1       0.93      0.64      0.76        22

    accuracy                           0.80        46
   macro avg       0.84      0.80      0.80        46
weighted avg       0.83      0.80      0.80        46



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [18]:
gnb=GaussianNB()


In [19]:
gnb.fit(x_train,y_train)
gnb.score(x_train,y_train)
predgnb=gnb.predict(x_test)
print(accuracy_score(y_test,predgnb))
print(confusion_matrix(y_test,predgnb))
print(classification_report(y_test,predgnb))

0.782608695652174
[[21  3]
 [ 7 15]]
              precision    recall  f1-score   support

           0       0.75      0.88      0.81        24
           1       0.83      0.68      0.75        22

    accuracy                           0.78        46
   macro avg       0.79      0.78      0.78        46
weighted avg       0.79      0.78      0.78        46



In [20]:
svc=SVC()

In [21]:
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=svc.predict(x_test)
print(accuracy_score(y_test,predsvc))
print(confusion_matrix(y_test,predsvc))
print(classification_report(y_test,predsvc))

0.8913043478260869
[[23  1]
 [ 4 18]]
              precision    recall  f1-score   support

           0       0.85      0.96      0.90        24
           1       0.95      0.82      0.88        22

    accuracy                           0.89        46
   macro avg       0.90      0.89      0.89        46
weighted avg       0.90      0.89      0.89        46



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [22]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
dt=DecisionTreeClassifier()

In [23]:
dt.fit(x_train,y_train)
dt.score(x_train,y_train)
preddt=dt.predict(x_test)
print(accuracy_score(y_test,preddt))
print(confusion_matrix(y_test,preddt))
print(classification_report(y_test,preddt))

0.6956521739130435
[[17  7]
 [ 7 15]]
              precision    recall  f1-score   support

           0       0.71      0.71      0.71        24
           1       0.68      0.68      0.68        22

    accuracy                           0.70        46
   macro avg       0.70      0.70      0.70        46
weighted avg       0.70      0.70      0.70        46



In [24]:
rbf=RandomForestClassifier()

In [25]:
rbf.fit(x_train,y_train)
rbf.score(x_train,y_train)
predrbf=dt.predict(x_test)
print(accuracy_score(y_test,predrbf))
print(confusion_matrix(y_test,predrbf))
print(classification_report(y_test,predrbf))

0.6956521739130435
[[17  7]
 [ 7 15]]
              precision    recall  f1-score   support

           0       0.71      0.71      0.71        24
           1       0.68      0.68      0.68        22

    accuracy                           0.70        46
   macro avg       0.70      0.70      0.70        46
weighted avg       0.70      0.70      0.70        46



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [27]:
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB() 
gnb.fit(x_train,y_train)
gnb.score(x_train,y_train)
predgnb=gnb.predict(x_test)
print(accuracy_score(y_test,predgnb))
print(confusion_matrix(y_test,predgnb))
print(classification_report(y_test,predgnb))

0.782608695652174
[[21  3]
 [ 7 15]]
              precision    recall  f1-score   support

           0       0.75      0.88      0.81        24
           1       0.83      0.68      0.75        22

    accuracy                           0.78        46
   macro avg       0.79      0.78      0.78        46
weighted avg       0.79      0.78      0.78        46



In [30]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
knn.score(x_train,y_train)
predknn=knn.predict(x_test)
print(accuracy_score(y_test,predknn))
print(confusion_matrix(y_test,predknn))
print(classification_report(y_test,predknn))

0.8260869565217391
[[22  2]
 [ 6 16]]
              precision    recall  f1-score   support

           0       0.79      0.92      0.85        24
           1       0.89      0.73      0.80        22

    accuracy                           0.83        46
   macro avg       0.84      0.82      0.82        46
weighted avg       0.84      0.83      0.82        46



So we conclude that from applying different algorithm we finf Support Vector Machine Classifier get the more accuracy it is about 90%